version: '3.8'

services:
  wacrm:
    container_name: wacrm-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NODE_TLS_REJECT_UNAUTHORIZED=0
